### ISSUE TITLE
【依頼】最終課題挙動確認

### ISSUE THREAD

**Issue by masuyosi** [masuyosi/freemarket_sample_71h#40]
■ URL
IPアドレス：http://18.177.133.178/
Github（最終課題のリポジトリ）：https://github.com/masuyosi/freemarket_sample_71h

■ Basic認証
ID：admin
Pass：2222

■ テスト用アカウント
◯ 購入者用
メールアドレス：buyer@example.com
パスワード：passwordb

◯ 購入用カード情報
番号：4242 4242 4242 4242
期限：01/30
セキュリティカード：000

◯ 出品者用
メールアドレス：seller@example.com
パスワード：passwords

**Comment by miyu-yamamoto** [comment]
提出ありがとうございます！
確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**○ カードの情報の登録ができない**
　→登録を何度か試みるも情報を入力して「追加する」を押すと情報が消えてしまう

**○ 新規ユーザー登録の際に住所を入力しているが、商品を購入しようとすると配送先が登録されていない旨のメッセージが表示される**
　→(登録してくださいをクリックしても無反応)
<img width="726" alt="スクリーンショット 2020-04-10 10 45 13" src="https://user-images.githubusercontent.com/59544869/78954887-7a545480-7b18-11ea-8212-355464e96a14.png">

**○ 出品されているものが人物や動物のため、服や家電などで出品し直しましょう**
<img width="982" alt="スクリーンショット 2020-04-10 10 47 13" src="https://user-images.githubusercontent.com/59544869/78954994-d3bc8380-7b18-11ea-9138-0f55503b4b91.png">

**○ 出品したもの編集画面にて画像を削除することができない(削除が表示されていない)**
<img width="647" alt="スクリーンショット 2020-04-10 10 50 44" src="https://user-images.githubusercontent.com/59544869/78955125-3dd52880-7b19-11ea-8c30-db7271dfab76.png">


修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfMuna4xX0zQ6_L8vRFrevse1I8VkCcdMp-24egzeH_JmIllg/viewform

**Comment by masuyosi** [comment]
>○ カードの情報の登録ができない
>　→登録を何度か試みるも情報を入力して「追加する」を押すと情報が消えてしまう

確認しましたが、登録可能でしたのでお手数ですがもう一度確認お願いします。
>○ 新規ユーザー登録の際に住所を入力しているが、商品を購入しようとすると配送先が登録され>ていない旨のメッセージが表示される

配送先の登録でバリデーションはかけていませんので、もう１度確認宜しくお願いします。
>○ 出品されているものが人物や動物のため、服や家電などで出品し直しましょう

DBリセットして出品し直しました！
>○ 出品したもの編集画面にて画像を削除することができない(削除が表示されていない)

[![Image from Gyazo](https://i.gyazo.com/67008122bba42fafcbc2477a0b29fdd8.gif)](https://gyazo.com/67008122bba42fafcbc2477a0b29fdd8)
チェックボックスを外して更新ボタンを押すことで削除されるように直しました。

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**Comment by masuyosi** [comment]
ありがとうございました！
